# Generated by Django 4.1 on 2022-08-17 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_userprofile_about'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='picture',
            new_name='foto',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='profile_id',
            new_name='id_perfil',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='name',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='profession',
            new_name='nome_usuario',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='username',
            new_name='profissao',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='about',
            new_name='sobre',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='user',
            new_name='usuario',
        ),
    ]
