# Generated by Django 4.1 on 2022-08-20 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_rename_picture_userprofile_foto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='usuario',
            field=models.SlugField(),
        ),
    ]
