# Generated by Django 4.1 on 2022-08-17 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmsapp', '0005_post_writer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='title',
            new_name='titulo',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='created',
            new_name='criado_em',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='writer',
            new_name='escritor',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='image',
            new_name='imagem',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='modified',
            new_name='modificado_em',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='body',
            new_name='texto',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='titulo',
        ),
    ]
